import numpy as np
import mdtraj as md
import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd
import glob
import os
import subprocess
import pexpect
import sys
import argparse
import scipy.constants as c
import matplotlib.ticker as ticker
import smtplib 
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
import zipfile

import tprgen as tg
import Contacts as cont
import PDBmod as pm
import maketable as table
import XTCconversion as xtc
import WHAM
import xvgenie as xvg
import BimodalTest as bt

def main():

    parser = argparse.ArgumentParser(description='Intake the working directory to generate, execute and analyze Gromacs files')
    parser.add_argument('directory', help='Path to the directory')
    args = parser.parse_args()

    # Use the directory argument
    directory_path = args.directory
    return directory_path

if __name__ == '__main__':
    wrkdir = main()
#----------------------------------------------------------------------------------------------------------------
# Settings
# 
# The script is designed to use the coarse grained files from the Smog-Server https://smog-server.org/prepare_a_simulation.html
#
# 
# the script is setup to take the working directory as an argument in the terminal i.e. python GMPP.py /path/to/working/directory
# or you can comment out lines 20-30 and uncomment line 40 to manually input the working directory in the script, keep in mind that if you do this you will have to change it
# every time you run the script for a new system 
#wrkdir = '/path/to/working/directory'

cut_off = 1.2
# cutoff = 1.2 means residues within 120% of their native range will be considered in contact for the Q(t) plot generated by contacts.py
# The range is only necessary for Calpha simulations, if using all atom simulations change cut_off to an integer value ~0.5 nm (5 Å) is standard. If you go less than 2 nm (not recommended) you will have to modify the code in contacts.py line 92
# you are free to change this range if it seems necessary, however 120% is a good starting point for most cases the minimum in contact distance is 70% of the native range
# to account for false positives in the simulation from misfolding or kinetic flucuation. 
trng = 80, 120
# trng is the starting range of temperatures you would like ot test your system with, 100-140K is a good starting point
#
dt = 1
# dt chooses the temeprature step in kelvin between each .tpr file
#
#r = 8.5
# r is the table length in nm
# 
# 
#
#
#----------------------------------------------------------------------------------------------------------------
# End Settings
#
output_folder = f'{wrkdir}/MDOutputFiles'
os.makedirs(output_folder, exist_ok = True)
failed = False
""" with open(f'{wrkdir}/GMPP log.txt', 'w') as f:
    f.write('GMPP log\n')
    f.write(f'Files will be saved to {output_folder}\n')
    f.write('Generating Potential Energy Lookup Table\n')
table.tablegen(r) """
#  
#
def run(trng):
    while True:
        try:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write('Generating TPR Files\n')
            tg.tprgen(trng, output_folder)
        except Exception as e:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write(f'Error generating TPR files: {e}\n')
                failed = True
                break
        # tprgen will generate and execute the tpr files for the range of temperatures in trng
        #
        #
        try:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write('Generating Coarse Grained PDBs for RMSD Analysis and .xtc Conversions\n')
            # coars graining a pdb for rmsd calculation; gromacs will throw an error when attempting to calculate rmsd of a calpha simulation with an all atom pdb
            pm.coarspdb(output_folder)
        except Exception as e:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write(f'Error generating coarse grained PDBs: {e}\n')
                failed = True
                break
        # xtc modifications for simpler analysis and smaller data sizes
        try:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write('Generating XTC Files\n')
            xtc.xtcmods(output_folder)
        except Exception as e:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write(f'Error generating XTC files: {e}\n')
                failed = True
                break
        # xvg generator WHAM integration and heat Cv determination
        try:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write('Generating XVG Files\n')
            xvg.xvgenie(output_folder)
        except Exception as e:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write(f'Error generating XVG files: {e}\n')
                failed = True
                break
        # Bimodality test to identify Tf
        
         
        try:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write('Performing Bimodality Test\n')
            bimodal, foldingtemp = bt.bimodal(output_folder)
            
            if bimodal == True:
                
                with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                    f.write(f'Tf = {foldingtemp} K\n')
                    f.write('Note: Due to lack of solvent, the folding temperature is significantly lower than in reality. The Q(t) and RMSD plots will show the fold populations')
                return foldingtemp
                
            if bimodal == False:
                if trng.min() == 80:
                    trngl = trng[0]+41
                    trngh = trng[1]+40
                    trng = trngl, trngh
                    with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                        f.write(f'Generating new TPR files for Temperature Range {trngl}-{trngh}\n')
                    run(trng)
                else:
                    trngl = 40
                    trngh = 79
                    trng = trngl, trngh
                    with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                        f.write(f'Generating new TPR files for Temperature Range {trngl}-{trngh}\n')
                    run(trng)
        except Exception as e:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write(f'Error performing bimodality test: {e}\n')
                failed = True
                break  
        # contact analysis for analyzing folding transitions
        try:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write('Performing Contact Analysis\n')
            q = cont.contact_analysis(cut_off, foldingtemp, wrkdir)
            with open(f'{wrkdir}/MDOutputFiles/contacts.txt', 'a') as f:
                f.write(f'Number of contacts framewise: \n')
                for i in q:
                    f.write(f'{i}\n')
                f.close()
        except Exception as e:
            with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
                f.write(f'Error performing contact analysis: {e}\n')
                failed = True
                break
def send_email(output_folder, wrkdir, sender_email, receiver_email, subject, body):
    zip_file_path = f'{output_folder}/GMPP.zip'
    with zipfile.ZipFile(zip_file_path, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        for root, dirs, files in os.walk(output_folder):
            for file in files:
                file_path = os.path.join(root, file)
                zip_file.write(file_path, os.path.relpath(file_path, output_folder))

    with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
        f.write(f'GMPP finished\n')

    msg = MIMEMultipart()
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = subject
    msg.attach(MIMEText(body, 'plain'))

    attachment = MIMEBase('application', 'octet-stream')
    attachment.set_payload(open(zip_file_path, 'rb').read())
    attachment.add_header('Content-Disposition', 'attachment; filename = %s' % zip_file_path)
    msg.attach(attachment)

    server = smtplib.SMTP('smtp.gmail.com', 587)
    server.starttls()
    server.login(sender_email, 'Ifthisdoesntworkimightscream')
    server.sendmail(sender_email, receiver_email, msg.as_string())
    server.quit()
        
sender_email = 'twatch@iastate.edu' # Need to make an email account for sending outputs and receiving comments/concerns
receiver_email = 'watchorntrevor@gmail.com' # arg parse the user email
subject = 'GMPP Output Files'
if failed == True:
    body = 'GMPP failed, please check log file for more information'
    with open(f'{wrkdir}/GMPP log.txt', 'a') as f:
        f.write('GMPP failed, please check log file for more information\n')
    send_email(output_folder, wrkdir, sender_email, receiver_email, subject, body)
else:
    # WHAM integration
    WHAM.wham(output_folder)
    body = 'GMPP finished, check log file for more information. Thank you for using the Go-Model Pressure Project!'
    send_email(output_folder, wrkdir, sender_email, receiver_email, subject, body)


# GB1, lysozyme, 1ubq mutant